name: Deploy Next.js to Firebase Hosting with Environment Variables
on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install Dependencies
        run: bun install

      - name: Create env file
        run: |
          echo "NEXT_PUBLIC_GUMLOOP_API_KEY=${{ secrets.NEXT_PUBLIC_GUMLOOP_API_KEY }}" >> .env
          echo "NEXT_PUBLIC_GUMLOOP_API_URL=${{ secrets.NEXT_PUBLIC_GUMLOOP_API_URL }}" >> .env
          echo "NEXT_PUBLIC_GUMLOOP_USER_ID=${{ secrets.NEXT_PUBLIC_GUMLOOP_USER_ID }}" >> .env
          echo "NEXT_PUBLIC_GUMLOOP_SAVED_ITEM_ID=${{ secrets.NEXT_PUBLIC_GUMLOOP_SAVED_ITEM_ID }}" >> .env
          echo "NEXT_PUBLIC_FIREBASE_API_KEY=${{ secrets.NEXT_PUBLIC_FIREBASE_API_KEY }}" >> .env
          echo "NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${{ secrets.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN }}" >> .env
          echo "NEXT_PUBLIC_FIREBASE_PROJECT_ID=${{ secrets.NEXT_PUBLIC_FIREBASE_PROJECT_ID }}" >> .env
          echo "NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=${{ secrets.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET }}" >> .env

      - name: Build
        run: bun run build

      - name: Export Static Files
        run: bun run export
        # Only needed if you're using static export. Remove if using SSR

      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          channelId: live
          projectId: ${{ secrets.NEXT_PUBLIC_FIREBASE_PROJECT_ID }}
          entryPoint: '.'